"""
decision_engine/engine.py
--------------------------
Rule-based shortage and wastage alert generation.

This module contains ZERO machine learning.
All decisions are deterministic rules applied to simulation outputs.

Risk Levels
-----------
  HIGH   — Immediate action required.
  MEDIUM — Monitor closely; take preventive action.
  LOW    — Within safe thresholds; no alert generated.

Alert Types
-----------
  SHORTAGE — Projected stock falls below safety threshold.
  WASTAGE  — Near-expiry units at risk of being wasted given low incoming demand.
"""

import logging
from dataclasses import dataclass
from datetime import date, timedelta
from typing import Dict, List

from sqlalchemy import func
from sqlalchemy.orm import Session

from config.settings import (
    BLOOD_GROUPS,
    SAFETY_STOCK_PER_GROUP,
    WASTAGE_EXPIRY_WINDOW_DAYS,
)
from database.db import InventoryBatch, RiskAlert
from inventory_simulation.simulation_engine import SimulationResult

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Alert dataclass (in-memory, before DB persistence)
# ---------------------------------------------------------------------------

@dataclass
class Alert:
    """
    An alert generated by the Decision Engine.

    Attributes
    ----------
    blood_group    : The ABO blood group this alert concerns.
    alert_type     : 'SHORTAGE' or 'WASTAGE'.
    risk_level     : 'LOW', 'MEDIUM', or 'HIGH'.
    message        : Human-readable description of the risk condition.
    recommendation : Concrete, actionable advice for hospital staff.
    """
    blood_group: str
    alert_type: str
    risk_level: str
    message: str
    recommendation: str


# ---------------------------------------------------------------------------
# Decision Engine
# ---------------------------------------------------------------------------

class DecisionEngine:
    """
    Evaluates post-simulation state and generates shortage and wastage alerts.

    Usage
    -----
    engine = DecisionEngine()
    alerts = engine.evaluate(db, sim_date, sim_result, donation_forecast)
    """

    def evaluate(
        self,
        db: Session,
        sim_date: date,
        sim_result: SimulationResult,
        donation_forecast: Dict[str, float],
    ) -> List[Alert]:
        """
        Run all decision rules and return a list of Alerts.

        Parameters
        ----------
        db               : Active SQLAlchemy session.
        sim_date         : The date just simulated.
        sim_result       : Output of SimulationEngine.run_simulation_day().
        donation_forecast : Per-group donations predicted for sim_date.

        Returns
        -------
        list[Alert]
            All alerts at MEDIUM or HIGH risk level.
            LOW risk events are not persisted to avoid alert fatigue.
        """
        alerts: List[Alert] = []

        for group in BLOOD_GROUPS:
            # --- Shortage evaluation ---
            shortage_alert = self._evaluate_shortage(group, sim_result, sim_date)
            if shortage_alert and shortage_alert.risk_level != "LOW":
                alerts.append(shortage_alert)

            # --- Wastage evaluation ---
            wastage_alert = self._evaluate_wastage(
                db, group, sim_date, donation_forecast
            )
            if wastage_alert and wastage_alert.risk_level != "LOW":
                alerts.append(wastage_alert)

        # Persist all non-LOW alerts
        self._persist_alerts(db, sim_date, alerts)

        logger.info(
            "Decision Engine: %d alert(s) generated for %s.",
            len(alerts), sim_date,
        )
        for alert in alerts:
            logger.info(
                "  [%s] %s — %s: %s",
                alert.risk_level, alert.alert_type,
                alert.blood_group, alert.message,
            )

        return alerts

    # ------------------------------------------------------------------
    # Shortage evaluation
    # ------------------------------------------------------------------

    def _evaluate_shortage(
        self,
        group: str,
        sim_result: SimulationResult,
        sim_date: date,
    ) -> Alert:
        """
        Compare projected stock to safety stock threshold.

        Thresholds
        ----------
        HIGH   : stock < 50% of safety stock
        MEDIUM : 50% of safety stock ≤ stock < 100% of safety stock
        LOW    : stock ≥ safety stock
        """
        stock = sim_result.projected_stock.get(group, 0)
        threshold = SAFETY_STOCK_PER_GROUP.get(group, 0)
        half_threshold = threshold / 2

        if stock < half_threshold:
            risk = "HIGH"
            message = (
                f"Blood group {group} is critically low: {stock} units available "
                f"(threshold: {threshold} units)."
            )
            recommendation = (
                f"URGENT: Organize an {group} donation drive within 48 hours. "
                f"Contact regional blood bank for emergency transfer of at least "
                f"{threshold - stock} units."
            )
        elif stock < threshold:
            risk = "MEDIUM"
            shortfall = threshold - stock
            message = (
                f"Blood group {group} is below safety threshold: {stock} units "
                f"(threshold: {threshold} units, shortfall: {shortfall})."
            )
            recommendation = (
                f"Monitor {group} inventory closely. Schedule a donation campaign "
                f"within 5 days. Consider procuring {shortfall} units from "
                f"regional blood bank as a precaution."
            )
        else:
            risk = "LOW"
            message = f"Blood group {group}: stock {stock} units is above threshold."
            recommendation = "No action required."

        return Alert(
            blood_group=group,
            alert_type="SHORTAGE",
            risk_level=risk,
            message=message,
            recommendation=recommendation,
        )

    # ------------------------------------------------------------------
    # Wastage evaluation
    # ------------------------------------------------------------------

    def _evaluate_wastage(
        self,
        db: Session,
        group: str,
        sim_date: date,
        donation_forecast: Dict[str, float],
    ) -> Alert:
        """
        Detect wastage risk: near-expiry units vs. incoming donation volume.

        A large incoming donation when batches are already near expiry
        signals potential wastage.

        Risk logic
        ----------
        Let ``expiring_units`` = sum of AVAILABLE units for this group
        expiring within WASTAGE_EXPIRY_WINDOW_DAYS days.

        Let ``incoming`` = donation_forecast[group] (units arriving today).

        HIGH   : expiring_units > 0 AND incoming > expiring_units × 1.5
        MEDIUM : expiring_units > 0 AND incoming > expiring_units
        LOW    : otherwise
        """
        window_end = sim_date + timedelta(days=WASTAGE_EXPIRY_WINDOW_DAYS)

        expiring_total = (
            db.query(func.sum(InventoryBatch.units))
            .filter(
                InventoryBatch.blood_group == group,
                InventoryBatch.status == "AVAILABLE",
                InventoryBatch.expiry_date >= sim_date,
                InventoryBatch.expiry_date <= window_end,
            )
            .scalar()
        ) or 0

        incoming = donation_forecast.get(group, 0.0)

        if expiring_total > 0 and incoming > expiring_total * 1.5:
            risk = "HIGH"
            message = (
                f"Blood group {group}: {expiring_total} units expire within "
                f"{WASTAGE_EXPIRY_WINDOW_DAYS} days. Incoming donations ({incoming:.0f} units) "
                f"far exceed near-expiry volume — high wastage risk."
            )
            recommendation = (
                f"Prioritize usage of all {group} batches expiring within "
                f"{WASTAGE_EXPIRY_WINDOW_DAYS} days ({expiring_total} units at risk). "
                f"Transfer excess incoming donations to partner blood banks. "
                f"Schedule elective {group} transfusions immediately."
            )
        elif expiring_total > 0 and incoming > expiring_total:
            risk = "MEDIUM"
            excess = incoming - expiring_total
            message = (
                f"Blood group {group}: {expiring_total} units expire within "
                f"{WASTAGE_EXPIRY_WINDOW_DAYS} days. Incoming donations ({incoming:.0f} units) "
                f"exceed near-expiry stock — moderate wastage risk."
            )
            recommendation = (
                f"Review {group} transfusion schedule to prioritise near-expiry batches. "
                f"Consider directing {excess:.0f} surplus incoming units to a "
                f"partner facility."
            )
        else:
            risk = "LOW"
            message = (
                f"Blood group {group}: wastage risk low "
                f"({expiring_total} near-expiry units, {incoming:.0f} incoming)."
            )
            recommendation = "No wastage action required."

        return Alert(
            blood_group=group,
            alert_type="WASTAGE",
            risk_level=risk,
            message=message,
            recommendation=recommendation,
        )

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _persist_alerts(
        self, db: Session, alert_date: date, alerts: List[Alert]
    ) -> None:
        """
        Save all alerts to the risk_alerts table.

        Only MEDIUM and HIGH alerts are persisted to avoid alert fatigue.
        """
        for alert in alerts:
            if alert.risk_level == "LOW":
                continue  # Do not clutter DB with routine non-events

            db_alert = RiskAlert(
                alert_date=alert_date,
                blood_group=alert.blood_group,
                alert_type=alert.alert_type,
                risk_level=alert.risk_level,
                message=alert.message,
                recommendation=alert.recommendation,
            )
            db.add(db_alert)

        db.commit()
