"""
database/db.py
--------------
SQLAlchemy ORM definitions and database session management.

Tables
------
  inventory_batches  – Physical blood bags in stock.
  forecast_demand    – XGBoost demand predictions stored per simulation day.
  forecast_donations – Prophet donation predictions stored per group per day.
  risk_alerts        – Shortage / wastage alerts generated by the Decision Engine.
"""

import uuid
import logging
from datetime import date, datetime
from typing import Generator

from sqlalchemy import (
    Column, String, Integer, Float, Date, DateTime,
    CheckConstraint, create_engine, text,
)
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from config.settings import DATABASE_URL, BLOOD_GROUPS

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Engine & session factory
# ---------------------------------------------------------------------------
engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False},  # required for SQLite + FastAPI
    echo=False,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


# ---------------------------------------------------------------------------
# Base class
# ---------------------------------------------------------------------------
class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Helper: blood group check constraint
# ---------------------------------------------------------------------------
_BLOOD_GROUP_CHECK = f"blood_group IN ({', '.join(repr(g) for g in BLOOD_GROUPS)})"


# ---------------------------------------------------------------------------
# Table 1: inventory_batches
# ---------------------------------------------------------------------------
class InventoryBatch(Base):
    """
    Represents one physical batch (collection unit) of blood in storage.

    Lifecycle
    ---------
    AVAILABLE  → blood is in stock and usable.
    CONSUMED   → units were used to satisfy demand during simulation.
    EXPIRED    → batch passed its expiry date before being consumed.
    """

    __tablename__ = "inventory_batches"

    id: int = Column(Integer, primary_key=True, index=True, autoincrement=True)
    batch_id: str = Column(
        String(36), unique=True, nullable=False, default=lambda: str(uuid.uuid4())
    )
    blood_group: str = Column(
        String(2),
        nullable=False,
        index=True,
    )
    units: int = Column(Integer, nullable=False)
    collection_date: date = Column(Date, nullable=False)
    expiry_date: date = Column(Date, nullable=False, index=True)
    status: str = Column(
        String(10),
        nullable=False,
        default="AVAILABLE",
    )

    __table_args__ = (
        CheckConstraint(_BLOOD_GROUP_CHECK, name="ck_inventory_blood_group"),
        CheckConstraint("units >= 0", name="ck_inventory_units_nonneg"),
        CheckConstraint(
            "status IN ('AVAILABLE', 'CONSUMED', 'EXPIRED')",
            name="ck_inventory_status",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<InventoryBatch batch_id={self.batch_id} "
            f"group={self.blood_group} units={self.units} "
            f"expires={self.expiry_date} status={self.status}>"
        )


# ---------------------------------------------------------------------------
# Table 2: forecast_demand
# ---------------------------------------------------------------------------
class ForecastDemand(Base):
    """
    Stores XGBoost daily demand predictions.

    One row per forecast date; refreshed each time /simulate is called.
    `predicted_units` is the total daily blood demand across all groups.
    """

    __tablename__ = "forecast_demand"

    id: int = Column(Integer, primary_key=True, index=True, autoincrement=True)
    forecast_date: date = Column(Date, nullable=False, index=True)
    predicted_units: float = Column(Float, nullable=False)
    created_at: datetime = Column(DateTime, nullable=False, default=datetime.utcnow)

    __table_args__ = (
        CheckConstraint("predicted_units >= 0", name="ck_demand_units_nonneg"),
    )

    def __repr__(self) -> str:
        return f"<ForecastDemand date={self.forecast_date} units={self.predicted_units:.1f}>"


# ---------------------------------------------------------------------------
# Table 3: forecast_donations
# ---------------------------------------------------------------------------
class ForecastDonation(Base):
    """
    Stores Prophet donation predictions per blood group per day.

    One row per (forecast_date, blood_group) pair.
    Four rows are inserted per simulation day (one per ABO group).
    """

    __tablename__ = "forecast_donations"

    id: int = Column(Integer, primary_key=True, index=True, autoincrement=True)
    forecast_date: date = Column(Date, nullable=False, index=True)
    blood_group: str = Column(String(2), nullable=False, index=True)
    predicted_units: float = Column(Float, nullable=False)
    created_at: datetime = Column(DateTime, nullable=False, default=datetime.utcnow)

    __table_args__ = (
        CheckConstraint(_BLOOD_GROUP_CHECK, name="ck_donation_blood_group"),
        CheckConstraint("predicted_units >= 0", name="ck_donation_units_nonneg"),
    )

    def __repr__(self) -> str:
        return (
            f"<ForecastDonation date={self.forecast_date} "
            f"group={self.blood_group} units={self.predicted_units:.1f}>"
        )


# ---------------------------------------------------------------------------
# Table 4: risk_alerts
# ---------------------------------------------------------------------------
class RiskAlert(Base):
    """
    Shortage and wastage alerts generated by the Decision Engine.

    alert_type : 'SHORTAGE' | 'WASTAGE'
    risk_level : 'LOW' | 'MEDIUM' | 'HIGH'
    """

    __tablename__ = "risk_alerts"

    id: int = Column(Integer, primary_key=True, index=True, autoincrement=True)
    alert_date: date = Column(Date, nullable=False, index=True)
    blood_group: str = Column(String(2), nullable=False, index=True)
    alert_type: str = Column(String(8), nullable=False)
    risk_level: str = Column(String(6), nullable=False, index=True)
    message: str = Column(String(512), nullable=False)
    recommendation: str = Column(String(512), nullable=False)
    created_at: datetime = Column(DateTime, nullable=False, default=datetime.utcnow)

    __table_args__ = (
        CheckConstraint(_BLOOD_GROUP_CHECK, name="ck_alert_blood_group"),
        CheckConstraint(
            "alert_type IN ('SHORTAGE', 'WASTAGE')", name="ck_alert_type"
        ),
        CheckConstraint(
            "risk_level IN ('LOW', 'MEDIUM', 'HIGH')", name="ck_alert_risk_level"
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<RiskAlert date={self.alert_date} group={self.blood_group} "
            f"type={self.alert_type} level={self.risk_level}>"
        )


# ---------------------------------------------------------------------------
# Database initialisation
# ---------------------------------------------------------------------------
def init_db() -> None:
    """Create all tables if they do not already exist."""
    logger.info("Initialising database schema...")
    Base.metadata.create_all(bind=engine)
    logger.info("Database schema ready.")


# ---------------------------------------------------------------------------
# Dependency: FastAPI-compatible session provider
# ---------------------------------------------------------------------------
def get_db() -> Generator[Session, None, None]:
    """
    Yield a SQLAlchemy session and guarantee it is closed after each request.
    Use as a FastAPI Depends() dependency.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
